### PR TITLE
Fix SimpleCouchbaseRepository not taking into account the default consistency.

### LINKED ISSUE #1243: Set default consistency at project level, per profile
According to the documentation, the default consistency level for Repositories is `NOT_BOUNDED` ( https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#couchbase.repository.consistency ).
This is fine for some environment, but not for others. Typically during tests, most of them fail because they try to read their own writes, and it fails.
With a previous version of Spring Data Couchbase based on SDK 2.x we could extend `getDefaultConsistency()` from `AbstractCouchbaseConfiguration`. This method is now gone and as we are migrating, it breaks our app. No green tests, no delivery.

### PR DESCRIPTION
**Pull request by JesusTheHun**
Setting default consistency should make all queries performed with said consistency. 

This PR fixes the issue and add a non-regression test.

Closes #1243 .

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

@pivotal-cla This is an Obvious Fix

### CODE REVIEW

File: src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java [hunk 1]
```diff
@@ -190,7 +191,12 @@ public void deleteAll() {
 	}
 
 	private QueryScanConsistency buildQueryScanConsistency() {
-		QueryScanConsistency scanConsistency = QueryScanConsistency.NOT_BOUNDED;
+		QueryScanConsistency scanConsistency = null;
+
+		if (couchbaseOperations.getConsistency() != null) {
+			scanConsistency = couchbaseOperations.getConsistency();
+		}
+
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java:199]: Only the first line is necessary.  The Reactive*OperationSupport.build*Options() will take consistency from the template (couchbaseOperations) if not otherwise set.

File: src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java [hunk 2]
```diff
@@ -57,20 +57,13 @@
...
-import org.springframework.data.couchbase.domain.PersonRepository;
-import org.springframework.data.couchbase.domain.User;
-import org.springframework.data.couchbase.domain.UserRepository;
+import org.springframework.data.couchbase.domain.*;
 import org.springframework.data.couchbase.domain.time.AuditingDateTimeProvider;
 import org.springframework.data.couchbase.repository.auditing.EnableCouchbaseAuditing;
 import org.springframework.data.couchbase.repository.config.EnableCouchbaseRepositories;
 import org.springframework.data.couchbase.repository.query.CouchbaseQueryMethod;
 import org.springframework.data.couchbase.repository.query.CouchbaseRepositoryQuery;
+import org.springframework.data.couchbase.repository.support.SimpleCouchbaseRepository;
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java:66]: Not needed?
