### PR TITLE
Log exceptions thrown from events.

### LINKED ISSUE #1075: CouchbaseTemplateSupport does not log exceptions thrown by CouchbaseMappingEvent Listeners correctly
`CouchbaseTemplateSupport#maybeEmitEvent` and `CouchbaseTemplateSupport#maybeCallBeforeConvert`

both contain

```java
			} catch (Exception e) {
				e.printStackTrace();
			}
```

### PR DESCRIPTION
**Pull request by mikereiche**
Closes #1075.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

File: src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java [hunk 1]
```diff
@@ -182,7 +182,7 @@ public void maybeEmitEvent(CouchbaseMappingEvent<?> event) {
 			try {
 				this.applicationContext.publishEvent(event);
 			} catch (Exception e) {
-				e.printStackTrace();
+				LOG.error("exception emitting event", e);
```
Comment (daschl) [inline src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java:185]: you could add the event to the log message so in logging you can figure out which event caused the error

File: src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java [hunk 2]
```diff
@@ -189,7 +189,7 @@ public void maybeEmitEvent(CouchbaseMappingEvent<?> event) {
 			try {
 				this.applicationContext.publishEvent(event);
 			} catch (Exception e) {
-				e.printStackTrace();
+				LOG.error("exception emitting event", e);
```
Comment (daschl) [inline src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java:192]: you could add the event to the log message so in logging you can figure out which event caused the error

**Review by daschl — CHANGES_REQUESTED** [review]
