### PR TITLE
To support jdk 16, add converters and module-info.

### LINKED ISSUE #1057: Illegal reflective access by org.springframework.util.ReflectionUtils
This occurs for certain property types in my entities.  Optional<String> and UUID.  The message that this will be denied in a future release is concerning.

This looks similar to https://github.com/spring-projects/spring-framework/issues/24999. A work-around for UUID is to declare the property as Object, but store it as a UUID.  This will/can result in it being set to a String by "accessor.setProperty(idProperty, generatedId);" in MappingCouchbaseConverter.writeInternal() and similarly by "accessor.setProperty(idProperty, id);" in CouchbaseTemplate.applyUpdatedId().  To accomodate that, getId() should always check for it being a String, and if so, replace it by id = UUID.fromString(id)
```
public UUID getId() {
	if (id != null && id.getClass()
			.equals(String.class)) {
		id = UUID.fromString((String) ((Object) id));
	}
	return (UUID)id;
}
```

java version 11.0.6.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/Users/michaelreiche/.m2/repository/org/springframework/spring-core/5.3.3/spring-core-5.3.3.jar) to constructor java.util.Optional()
WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

with --illegal-access=debug 

```
AccessibleObject

 private boolean checkCanSetAccessible(Class<?> caller, Class<?> declaringClass, boolean throwExceptionIfDenied)
. . .
        if (declaringModule.isOpen(pn, callerModule)) {
131:          this.logIfOpenedForIllegalAccess(caller, declaringClass); <-- warning output here
          return true;
        } else if (throwExceptionIfDenied) {

WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/Users/michaelreiche/.m2/repository/org/springframework/spring-core/5.3.3/spring-core-5.3.3.jar) to constructor java.util.Optional()
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/Users/michaelreiche/.m2/repository/org/springframework/spring-core/5.3.3/spring-core-5.3.3.jar) to field java.util.Optional.value
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/Users/michaelreiche/.m2/repository/org/springframework/spring-core/5.3.3/spring-core-5.3.3.jar) to field java.util.UUID.mostSigBits
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/Users/michaelreiche/.m2/repository/org/springframework/spring-core/5.3.3/spring-core-5.3.3.jar) to field java.util.UUID.leastSigBits

public class BasicCouchbasePersistentEntity<T> extends BasicPersistentEntity<T, CouchbasePersistentProperty>
		implements CouchbasePersistentEntity<T>, EnvironmentAware {

	public BasicCouchbasePersistentEntity(final TypeInformation<T> typeInformation) {
>> 50:		super(typeInformation);
		validateExpirationConfiguration();
	}

WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (file:/Users/michaelreiche/.m2/repository/org/springframework/spring-core/5.3.3/spring-core-5.3.3.jar) to constructor java.util.Optional()
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:202)
	at org.springframework.data.mapping.PreferredConstructor.<init>(PreferredConstructor.java:63)
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.buildPreferredConstructor(PreferredConstructorDiscoverer.java:204)
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.access$200(PreferredConstructorDiscoverer.java:91)
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers$1.discover(PreferredConstructorDiscoverer.java:130)
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer.discover(PreferredConstructorDiscoverer.java:79)
	at org.springframework.data.mapping.model.BasicPersistentEntity.<init>(BasicPersistentEntity.java:112)
	at org.springframework.data.mapping.model.BasicPersistentEntity.<init>(BasicPersistentEntity.java:93)
	at org.springframework.data.couchbase.core.mapping.BasicCouchbasePersistentEntity.<init>(BasicCouchbasePersistentEntity.java:50)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.createPersistentEntity(CouchbaseMappingContext.java:74)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.createPersistentEntity(CouchbaseMappingContext.java:37)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:368)
	at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4797)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:564)

@Document
public class Person extends AbstractEntity {
	@Nullable Optional<String> firstname;

	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:522)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:708)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:385)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:259)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:202)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:86)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:324)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:324)
	at org.springframework.data.couchbase.repository.support.CouchbaseRepositoryFactoryBean.afterPropertiesSet(CouchbaseRepositoryFactoryBean.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

```

### PR DESCRIPTION
**Pull request by mikereiche**
target 9 is necessary to support module info.  module info is necessary to specify the various requires/opens/exports.
Converters for BigInteger and UUID have been added in OtherConverters.  
The constructor for MappingCouchbaseConverter has been modified to (1) include the CouchbaseCustomConverters; and (2) specify the SimpleTypes of the converters. Prior to this change, couchbaseMappingContext Bean and mappingCouchbaseConverter Bean in AbstractCouchbaseConfiguration were relied upon for doing this.

Closes #1057.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mp911de** [comment]
For the time being, we cannot include this change as projects are required to remain Java 8-compatible. Setting the release version to `9` produces classes using the Java 9 bytecode version and that is going to break Spring Boot compatibility.

Furthermore, we do not plan to add module descriptors across Spring projects. Once we agree to do so, we will have to make sure to come up with a consistent design for all modules.

**Comment by mikereiche** [comment]
Mark - I've removed target 9 and the module-info.java. So this just has the added converters and related changes and it does run with jdk 16 without errors.

File: src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java [hunk 1]
```diff
@@ -145,8 +142,14 @@ public MappingCouchbaseConverter(
...
 		super(new DefaultConversionService());
-
 		this.mappingContext = mappingContext;
+		// this is how the MappingCouchbaseConverter gets the custom conversions.
+		// the conversions Service gets them in afterPropertiesSet()
+		CustomConversions customConversions = new CouchbaseCustomConversions(Collections.emptyList());
+		this.setCustomConversions(customConversions);
+		// if the mappingContext does not have the SimpleTypes, it will not know that they have converters, then it will
+		// try to access the fields of the type and (maybe) fail with InaccessibleObjectException
+		((CouchbaseMappingContext) mappingContext).setSimpleTypeHolder(customConversions.getSimpleTypeHolder());
```
Comment (mp911de) [inline src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java:152]: While this would work, associating custom conversions should happen outside the converter. Typically, `CustomConversions` gets configured by users, and then it should get associated with the converter/mapping context within `@Bean` methods.

File: src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+
+		converters.add(UuidToString.INSTANCE);
+		converters.add(StringToUuid.INSTANCE);
+		converters.add(BigIntegerToString.INSTANCE);
+		converters.add(StringToBigInteger.INSTANCE);
+
+		return converters;
+	}
+
+	@WritingConverter public enum UuidToString implements Converter<UUID,String>
```
Comment (mp911de) [inline src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java:54]: Please properly format this file.

File: src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java [hunk 3]
```diff
@@ -131,12 +132,21 @@ public void setAutoIndexCreation(boolean autoCreateIndexes) {
...
+	 *
 	 * @param typeInformation - entity type
 	 */
 	@Override
 	protected Optional<BasicCouchbasePersistentEntity<?>> addPersistentEntity(TypeInformation<?> typeInformation) {
-		Optional<BasicCouchbasePersistentEntity<?>> entity = super.addPersistentEntity(typeInformation);
+		Optional<BasicCouchbasePersistentEntity<?>> entity = null;
+		try {
+			entity = super.addPersistentEntity(typeInformation);
+		} catch (Exception ioe) {
```
Comment (mp911de) [inline src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java:143]: That shouldn't be here.

File: src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java (hunk 2 above)
Comment (mikereiche) [reply src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java:54]: Oops. Fixed in next push.

File: src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java (hunk 3 above)
Comment (mikereiche) [reply src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java:143]: Ok. I've changed the test case that is expecting MappingException to also expect IllegalObjectAccessException.

File: src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java (hunk 1 above)
Comment (mikereiche) [reply src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java:152]: They were already populated in AbstractCouchbaseConverter.
```
	protected CustomConversions conversions = new CouchbaseCustomConversions(Collections.emptyList());
```
I set them again in the MappingCouchbaseConverter constructor so that the mappingContext could capture the SimpleTypes so those converters would be used. 

btw - these aren't strictly user-supplied "custom" conversions. These are provided/required by couchbase (and also  included in any customer-created CouchbaseCustomConversions).
