### PR TITLE
Fix serialization for field level encryption.

### LINKED ISSUE #1621: revisit serialization/deserialization in CryptoConverter
revisit serialization/deserialization in CryptoConverter.
It currently will ignore @JsonValue annotations on Enums.

### PR DESCRIPTION
**Pull request by mikereiche**
The key changes are at lines 141 and 145 of CryptoConverter.

(a) use objectMapper to encode strings instead of just escaping and adding quotes; and
(b) use context.getConverter().writeInternalRoot() to serialize instead of 
 relying on context.read(value).toString()) which relies on the entity object having a toString() that produces json.

Closes #1621.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mikereiche** [comment]
@dnault

File: src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java [hunk 1]
```diff
@@ -26,8 +26,6 @@
 import java.util.Map;
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java:26]: The CryptoConverter now needs the ObjectMapper.

File: src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java [hunk 2]
```diff
@@ -160,15 +160,16 @@ public Object convertForWriteIfNeeded(Object inValue) {
...
 		} else if (value instanceof Collection || elementType.isArray()) {
 			TypeInformation<?> type = ClassTypeInformation.from(value.getClass());
 			value = ((MappingCouchbaseConverter) this).writeCollectionInternal(MappingCouchbaseConverter.asCollection(value),
 					new CouchbaseList(conversions.getSimpleTypeHolder()), type, null, null);
 		} else {
 			CouchbaseDocument embeddedDoc = new CouchbaseDocument();
 			TypeInformation<?> type = ClassTypeInformation.from(value.getClass());
-			((MappingCouchbaseConverter) this).writeInternalRoot(value, embeddedDoc, type, false, null);
+			((MappingCouchbaseConverter) this).writeInternalRoot(value, embeddedDoc, type, false, null, true);
 			value = embeddedDoc;
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java:173]: writeInternalRoot needs a flag of whether or not to process PropertyValueConverters (specifically the CryptoConverter) so it doesn't recursively encrypt such an annotated property.

File: src/main/java/org/springframework/data/couchbase/core/convert/CouchbasePropertyValueConverterFactory.java [hunk 3]
```diff
@@ -31,7 +31,7 @@
 import com.couchbase.client.core.encryption.CryptoManager;
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/core/convert/CouchbasePropertyValueConverterFactory.java:31]: Addition of ObjectMapper.

File: src/main/java/org/springframework/data/couchbase/core/convert/CryptoConverter.java [hunk 4]
```diff
@@ -81,22 +82,12 @@ private Object coerceToValueRead(byte[] decrypted, CouchbaseConversionContext co
...
 		}
-		// TODO - as-is, this never gets ran through ObjectMapper() -
-		// TODO - i.e. @JsonValue etc will not be processed by ObjectMapper
-
-		/* this what we would do if we could use a JsonParser with a beanPropertyTypeRef
-		    final JsonParser plaintextParser = p.getCodec().getFactory().createParser(plaintext);
-		plaintextParser.setCodec(p.getCodec());
-		
-		return plaintextParser.readValueAs(beanPropertyTypeRef);
-		 */
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/core/convert/CryptoConverter.java:91]: The deleted comment is a bit misleading.  The conversions do take place in context.getConverter.read() and getPotentiallyConvertedSimpleRead() below.

File: src/main/java/org/springframework/data/couchbase/core/convert/CryptoConverter.java [hunk 5]
```diff
@@ -133,16 +124,20 @@ private byte[] coerceToBytesWrite(CouchbasePersistentProperty property, Converti
...
+					throw new RuntimeException(e);
+				}
 			}
 			plainText = plainString.getBytes(StandardCharsets.UTF_8);
 		} else { // an entity
-			plainText = JsonObject.fromJson(context.read(value).toString().getBytes(StandardCharsets.UTF_8)).toBytes();
+			CouchbaseDocument doc = new CouchbaseDocument();
+			context.getConverter().writeInternalRoot(value, doc, property.getTypeInformation(), false, property, false);
+			plainText = JsonObject.from(doc.export()).toBytes();
 		}
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/core/convert/CryptoConverter.java:141]: The old code relied on the entity (Airport, Address etc) produced by context.read(value) have a nice toString() method that gives the json representation of the object.  It's a bad assumption.

File: src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java [hunk 6]
```diff
@@ -566,7 +567,7 @@ public void doWithAssociation(final Association<CouchbasePersistentProperty> ass
 			}
 		});
 
-		if (prop != null && conversions.hasValueConverter(prop)) { // whole entity is encrypted
+		if (prop != null && processValueConverter && conversions.hasValueConverter(prop)) { // whole entity is encrypted
 			Map<String, Object> propertyConverted = (Map<String, Object>) conversions.getPropertyValueConversions()
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java:571]: This will prevent recursively encrypting an annotated property.

File: src/test/java/org/springframework/data/couchbase/domain/Address.java [hunk 7]
```diff
@@ -15,7 +15,6 @@
  */
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/domain/Address.java:15]: Add one of our @JsonValue Enums to Address which gets used in the FLE tests and elsewhere.

File: src/test/java/org/springframework/data/couchbase/domain/ETurbulenceCategory.java [hunk 8]
```diff
@@ -23,7 +23,7 @@
  * @author Michael Reiche
  */
 public enum ETurbulenceCategory {
-	T10("10%"), T20("20%"), T30("30%");
+	T10("\"10%"), T20("\"20%"), T30("\"30%");
 
 	private final String code;
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/domain/ETurbulenceCategory.java:29]: Add a quote to the content of the Enum serialization.

File: src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java [hunk 9]
```diff
@@ -137,6 +137,7 @@ public UserEncrypted(final String id, final String firstname, final String lastn
 	@Encrypted public UUID encUUID;
 	@Encrypted public DateTime encDateTime;
 
+	@Encrypted public ETurbulenceCategory turbulence;
 	@Encrypted public Address encAddress = new Address();
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java:141]: Add an encrypted @JsonValue Enum.

File: src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java [hunk 10]
```diff
@@ -228,8 +229,8 @@ public void initSimpleTypes() {
 		encCharacter = 'a';
 		encCharacters = new Character[] { 'a', 'b' };
 
-		encString = "myString";
-		encStrings = new String[] { "myString" };
+		encString = "myS\"tring";
+		encStrings = new String[] { "mySt\"ring" };
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java:233]: make a tricky String and String array

File: src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java [hunk 11]
```diff
@@ -248,13 +249,12 @@ public void initSimpleTypes() {
 		//clazz = String.class;
 
 		encDateTime = NOW_DateTime;
-
-		encAddress = new Address();
-
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java:253]: let the caller (test case) initialize this.
