### PR TITLE
Expose ObjectMapper used by JsonSerializer

### LINKED ISSUE #1130: add couchbaseJsonValueModule bean to AbstractCouchbaseConfiguration
https://forums.couchbase.com/t/setting-json-deserialisation-features-in-java-sdk-3/30215/6

We Could change contentAsObject() to always use JacksonTransformers.bytesToJsonObject() so it doesn't depend on the user registering the correct module. What do you think?
Should also add another preflight check and fail if JsonValueModule isn't registered.

### PR DESCRIPTION
**Pull request by mikereiche**
Expose ObjectMapper used by JsonSerializer

Closes #1130.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

File: src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java [hunk 1]
```diff
@@ -130,6 +140,10 @@ public Cluster couchbaseCluster(ClusterEnvironment couchbaseClusterEnvironment)
 	@Bean(destroyMethod = "shutdown")
 	public ClusterEnvironment couchbaseClusterEnvironment() {
 		ClusterEnvironment.Builder builder = ClusterEnvironment.builder();
+		if (!nonShadowedJacksonPresent()) {
+			throw new CouchbaseException("non-shadowed Jackson not present");
+		}
+		builder.jsonSerializer(JacksonJsonSerializer.create(couchbaseObjectMapper));
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java:146]: use the couchbaseObjectMapper from the new Bean.
Check for nonShadowedJacksonPresent() although it should never happen.

File: src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java [hunk 2]
```diff
@@ -273,6 +287,31 @@ public CouchbaseMappingContext couchbaseMappingContext(CustomConversions customC
...
+		ObjectMapper mapper = new ObjectMapper();
+		mapper.configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
+		mapper.registerModule(new JsonValueModule());
+		CryptoManager cryptoManager = null;
+		if (cryptoManager != null) {
+			mapper.registerModule(new EncryptionModule(cryptoManager));
+		}
+		return mapper;
+	}
+
```
Comment (mikereiche) [inline src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java:314]: the couchbaseObjectMapper that gets used and exposed. Created the same as in ClusterEnvironment.Builder.

File: src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java [hunk 3]
```diff
@@ -184,6 +184,7 @@ void findByTypeAlias() {
 			vie = new Airport("airports::vie", "vie", "loww");
 			vie = airportRepository.save(vie);
 			List<Airport> airports = couchbaseTemplate.findByQuery(Airport.class)
+					.withConsistency(QueryScanConsistency.REQUEST_PLUS)
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java:187]: fixed a test that was sporadically failing.

File: src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java [hunk 4]
```diff
@@ -198,7 +199,7 @@ void findByEnum() {
 			vie = new Airport("airports::vie", "vie", "loww");
 			vie = airportRepository.save(vie);
 			Airport airport2 = airportRepository.findByIata(Iata.vie);
-			assertNotNull(airport2, "should have found "+vie);
+			assertNotNull(airport2, "should have found " + vie);
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java:202]: formatting.  Nothing to see.

File: src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java [hunk 5]
```diff
@@ -64,13 +66,13 @@ void saveAndFindById() {
...
-	void findBySimplePropertyAudited() {
+	void findByIdAudited() {
 		Airport vie = null;
 		try {
 			vie = new Airport("airports::vie", "vie", "low2");
 			Airport saved = airportRepository.save(vie).block();
-			List<Airport> airports1 = airportRepository.findAllByIata("vie").collectList().block();
-			assertEquals(saved, airports1.get(0));
+			Airport airport1 = airportRepository.findById(saved.getId()).block();
+			assertEquals(airport1, saved);
```
Comment (mikereiche) [inline src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java:75]: This was using a query which requires an index, but if you run this test by itself, there won't be an index.  Switch to use kv.

File: src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java [hunk 6]
```diff
@@ -130,6 +140,10 @@ public Cluster couchbaseCluster(ClusterEnvironment couchbaseClusterEnvironment)
 	@Bean(destroyMethod = "shutdown")
 	public ClusterEnvironment couchbaseClusterEnvironment() {
 		ClusterEnvironment.Builder builder = ClusterEnvironment.builder();
+		if (!nonShadowedJacksonPresent()) {
+			throw new CouchbaseException("non-shadowed Jackson not present");
```
Comment (daschl) [inline src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java:144]: is there a reason we need to blow up if it is not present? (or just add the custom serializer if present?) -  could log a warning instead if unlikely?

File: src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java [hunk 7]
```diff
@@ -273,6 +287,31 @@ public CouchbaseMappingContext couchbaseMappingContext(CustomConversions customC
...
+	/**
+	 * Creates a {@link Module} ObjectMapper mapper = new ObjectMapper();
+	 * mapper.registerModule(couchbaseJsonValueModule()); <----- ClusterEnvironment env = ClusterEnvironment.builder()
+	 * .jsonSerializer(new JacksonJsonSerializer(mapper)) .build();
+	 *
+	 * @throws Exception on Bean construction failure.
+	 * @return
+	 */
+	@Bean
+	public com.couchbase.client.core.deps.com.fasterxml.jackson.databind.Module couchbaseJsonValueModule() {
```
Comment (daschl) [inline src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java:299]: does this have to be its own bean?

**Review by daschl — COMMENTED** [review]
Some clarifications/input

File: src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java (hunk 6 above)
Comment (mikereiche) [reply src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java:144]: Good question. In the SDK, when the non-shadowed jackson classes are not present, a DefaultJsonSerializer is created.  DefaultJsonSerializer has no means to use an already-created mapper, or expose the mapper that it creates.  I suppose this would only be an issue when the user wants to us couchbaseObjectMapper() and expects it to be the same one used by the serializer.  However, David said the not having the non-shadowed classes in Spring is impossible.  The alternative would be to issue a warning saying that the serializer was not using couchbaseObjectMapper() and continue.

   return nonShadowedJacksonPresent()
        ? JacksonJsonSerializer.create(cryptoManager)
        : DefaultJsonSerializer.create(cryptoManager);

File: src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java (hunk 7 above)
Comment (mikereiche) [reply src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java:299]: This doesn't need to exist at all. Removed.
